from Lista import Lista

lista = Lista()
# lista.imprimir()
lista.add("Maria")
lista.add("João")
lista.add("Arthur")
lista.imprimir()
# lista.add("Maria")
# lista.add("Bibiana")
# lista.add("José")
# lista.imprimir()
# lista.remover("José")
# lista.imprimir()
# lista.remover("Carlos")